use customer_behaviour;

SELECT * FROM customer;

-- 1. Total Revenue Generated by Gender --
SELECT 
    gender, SUM(purchase_amount)
FROM
    customer
GROUP BY gender;

-- 2. Customers that used discount but still spent more than avg. purchase --
SELECT 
    customer_id, purchase_amount
FROM
    customer
WHERE
    discount_applied = 'Yes'
        AND purchase_amount >= (SELECT 
            AVG(purchase_amount)
        FROM
            customer);

-- 3. Top 5 customers with highest average review rating --
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS Average_Review_Rating
FROM
    customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5; 

-- 4. Average Purchase amt for standard and express shipping --
SELECT 
    shipping_type, AVG(purchase_amount)
FROM
    customer
WHERE
    shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type; 

-- 5. Compare avg. spend and total revenue between subscribers and non-subscribers --
SELECT 
    subscription_status,
    COUNT(customer_id),
    AVG(purchase_amount) AS Average_Spend,
    SUM(purchase_amount) AS Total_Revenue
FROM
    customer
GROUP BY subscription_status;
 
 -- 6. 5 products that have highest purchase % with discount applied
SELECT 
    item_purchased,
    SUM(CASE
        WHEN discount_applied = 'Yes' THEN 1
        ELSE 0
    END) / COUNT(*) * 100 AS discount_rate
FROM
    customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- 7. Segment Customers into New, Returning and Loyal based on previous purchases and show the count --

with customer_type as
(
SELECT 
    customer_id,
    previous_purchases,
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment
FROM
    customer)

SELECT 
    customer_segment, COUNT(*) AS Number
FROM
    customer_type
GROUP BY customer_segment;

-- 8. Top 3 most purchased products in each category -- 
with item_counts as (
select category, item_purchased, count(customer_id)  as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased)

SELECT 
    item_rank, category, item_purchased, total_orders
FROM
    item_counts
WHERE
    item_rank <= 3;

-- 9. Are cusotmers who are repeat buyers(more than 5 previous purchases) also likely to subscribe? --

SELECT 
    subscription_status, COUNT(customer_id) AS repeat_buyers
FROM
    customer
WHERE
    previous_purchases > 5
GROUP BY subscription_status;

-- 10. Revenue Contribution of each age group --

select age_group, sum(purchase_amount) as Revenue from customer
group by age_group;